<?php

/**
 * Copyright 2013-2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 *
 * @category Horde
 * @package  Components
 * @author   Ralf Lang <ralf.lang@ralf-lang.de>
 * @license  http://www.horde.org/licenses/lgpl21 LGPL 2.1
 */

declare(strict_types=1);

namespace Horde\Components\Ci\Setup;

use Horde\Components\Output;

/**
 * Generates executable shell scripts for test lanes.
 *
 * Creates bash scripts that execute QC tools (PHPUnit, PHPStan, PHP-CS-Fixer)
 * in a specific test lane configuration.
 *
 * @category Horde
 * @package  Components
 * @author   Ralf Lang <ralf.lang@ralf-lang.de>
 * @license  http://www.horde.org/licenses/lgpl21 LGPL 2.1
 */
class LaneScriptGenerator
{
    /**
     * Constructor.
     *
     * @param Output $output Output handler
     */
    public function __construct(
        private readonly Output $output
    ) {}

    /**
     * Generate execution script for a test lane.
     *
     * @param string $scriptPath Output path (e.g., /tmp/horde-ci/lanes/php8.4-dev/run-lane.sh)
     * @param array<string,mixed> $config Lane configuration
     * @return bool True if successful
     */
    public function generate(string $scriptPath, array $config): bool
    {
        // Validate required configuration keys
        $requiredKeys = ['lane_name', 'php_version', 'php_binary', 'tool_php_binary', 'stability', 'component_dir', 'tools_dir', 'build_dir'];
        foreach ($requiredKeys as $key) {
            if (!isset($config[$key])) {
                $this->output->error("Missing required config key: {$key}");
                return false;
            }
        }

        // Determine which tasks to run for this lane
        $tasks = $this->determineTasks($config);

        // Generate script content
        $script = $this->generateScriptContent($config, $tasks);

        // Write script to file
        $dir = dirname($scriptPath);
        if (!is_dir($dir) && !@mkdir($dir, 0o755, true) && !is_dir($dir)) {
            $this->output->error("Failed to create directory: {$dir}");
            return false;
        }

        if (file_put_contents($scriptPath, $script) === false) {
            $this->output->error("Failed to write script: {$scriptPath}");
            return false;
        }

        // Make script executable
        if (!chmod($scriptPath, 0o755)) {
            $this->output->error("Failed to make script executable: {$scriptPath}");
            return false;
        }

        return true;
    }

    /**
     * Determine which QC tasks to run for a lane.
     *
     * @param array<string,mixed> $laneConfig Lane configuration
     * @return array<string> Task names (e.g., ['unit', 'phpstan', 'phpcsfixer'])
     */
    private function determineTasks(array $laneConfig): array
    {
        $tasks = ['phpunit', 'phpstan'];

        // PHP-CS-Fixer only runs on PHP 8.4 dev lane
        if ($laneConfig['php_version'] === '8.4' && $laneConfig['stability'] === 'dev') {
            $tasks[] = 'phpcsfixer';
        }

        return $tasks;
    }

    /**
     * Generate the complete script content.
     *
     * @param array<string,mixed> $config Lane configuration
     * @param array<string> $tasks Tasks to include
     * @return string Script content
     */
    private function generateScriptContent(array $config, array $tasks): string
    {
        $laneName = $config['lane_name'];
        $phpVersion = $config['php_version'];
        $phpBinary = $config['php_binary'];
        $toolPhpBinary = $config['tool_php_binary'];
        $stability = $config['stability'];
        $componentDir = $config['component_dir'];
        $toolsDir = $config['tools_dir'];
        $buildDir = $config['build_dir'];
        $componentsPath = $config['components_path'] ?? '/usr/bin/horde-components';

        $timestamp = date('Y-m-d H:i:s T');

        $script = <<<BASH
            #!/bin/bash
            # Generated by: horde-components ci setup
            # Lane: {$laneName}
            # PHP: {$phpVersion}
            # Stability: {$stability}
            # Generated: {$timestamp}

            set -e
            set -o pipefail

            LANE_NAME="{$laneName}"
            # TOOL_PHP runs horde-components.phar; must satisfy its own
            # composer platform (>=8.2). LANE_PHP is what the tool
            # subprocess-invokes for PHPUnit/PHPStan/PHP-CS-Fixer under
            # this lane's target PHP.
            TOOL_PHP="{$toolPhpBinary}"
            LANE_PHP="{$phpBinary}"
            # Back-compat alias; remove after one release cycle.
            PHP_BINARY="\$LANE_PHP"
            COMPONENT_DIR="{$componentDir}"
            TOOLS_DIR="{$toolsDir}"
            BUILD_DIR="{$buildDir}"
            COMPONENTS_PATH="{$componentsPath}"

            # Ensure build directory exists
            mkdir -p "\$BUILD_DIR"

            cd "\$COMPONENT_DIR"


            BASH;

        // Add each task
        foreach ($tasks as $task) {
            $script .= $this->generateTaskSection($task, $phpVersion);
        }

        // Add summary section
        $script .= $this->generateSummarySection($tasks);

        return $script;
    }

    /**
     * Generate script section for a specific task.
     *
     * @param string $task Task name
     * @param string $phpVersion PHP version
     * @return string Script section
     */
    private function generateTaskSection(string $task, string $phpVersion): string
    {
        switch ($task) {
            case 'phpunit':
                return $this->generatePhpUnitSection($phpVersion);
            case 'phpstan':
                return $this->generatePhpStanSection();
            case 'phpcsfixer':
                return $this->generatePhpCsFixerSection();
            default:
                return '';
        }
    }

    /**
     * Generate PHPUnit task section.
     *
     * @param string $phpVersion PHP version
     * @return string Script section
     */
    private function generatePhpUnitSection(string $phpVersion): string
    {
        return <<<'BASH'
            # Task: PHPUnit
            echo "=== Running PHPUnit ==="
            cd "$COMPONENT_DIR"
            "$TOOL_PHP" "$COMPONENTS_PATH" qc unit \
                --tools-dir="$TOOLS_DIR" \
                --php="$LANE_PHP" \
                2>&1 || PHPUNIT_EXIT=$?
            # JSON written to: $BUILD_DIR/phpunit-results-summary.json


            BASH;
    }

    /**
     * Generate PHPStan task section.
     *
     * @return string Script section
     */
    private function generatePhpStanSection(): string
    {
        return <<<'BASH'
            # Task: PHPStan
            echo "=== Running PHPStan ==="
            cd "$COMPONENT_DIR"
            "$TOOL_PHP" "$COMPONENTS_PATH" qc phpstan \
                --tools-dir="$TOOLS_DIR" \
                --php="$LANE_PHP" \
                --dump-native \
                2>&1 || PHPSTAN_EXIT=$?
            # JSON written to: $BUILD_DIR/phpstan-results.json
            # Native JSON written to: $BUILD_DIR/phpstan-native.json (--dump-native)


            BASH;
    }

    /**
     * Generate PHP-CS-Fixer task section.
     *
     * @return string Script section
     */
    private function generatePhpCsFixerSection(): string
    {
        return <<<'BASH'
            # Task: PHP-CS-Fixer
            echo "=== Running PHP-CS-Fixer ==="
            cd "$COMPONENT_DIR"
            "$TOOL_PHP" "$COMPONENTS_PATH" qc phpcsfixer \
                --tools-dir="$TOOLS_DIR" \
                --php="$LANE_PHP" \
                2>&1 || PHPCS_EXIT=$?
            # JSON written to: $BUILD_DIR/php-cs-fixer-results.json


            BASH;
    }

    /**
     * Generate summary section with exit code handling.
     *
     * @param array<string> $tasks Tasks that were run
     * @return string Script section
     */
    private function generateSummarySection(array $tasks): string
    {
        $summary = <<<'BASH'
            # Summary
            echo ""
            echo "=== Lane $LANE_NAME Summary ==="

            BASH;

        // Add exit code display for each task
        if (in_array('phpunit', $tasks)) {
            $summary .= 'echo "PHPUnit exit: ${PHPUNIT_EXIT:-0}"' . "\n";
        }
        if (in_array('phpstan', $tasks)) {
            $summary .= 'echo "PHPStan exit: ${PHPSTAN_EXIT:-0}"' . "\n";
        }
        if (in_array('phpcsfixer', $tasks)) {
            $summary .= 'echo "PHP-CS-Fixer exit: ${PHPCS_EXIT:-0}"' . "\n";
        }

        $summary .= "\n# Exit with first non-zero exit code\n";

        // Add exit code checks
        if (in_array('phpunit', $tasks)) {
            $summary .= '[ "${PHPUNIT_EXIT:-0}" -ne 0 ] && exit "$PHPUNIT_EXIT"' . "\n";
        }
        if (in_array('phpstan', $tasks)) {
            $summary .= '[ "${PHPSTAN_EXIT:-0}" -ne 0 ] && exit "$PHPSTAN_EXIT"' . "\n";
        }
        if (in_array('phpcsfixer', $tasks)) {
            $summary .= '[ "${PHPCS_EXIT:-0}" -ne 0 ] && exit "$PHPCS_EXIT"' . "\n";
        }

        $summary .= "\necho \"All tasks passed!\"\nexit 0\n";

        return $summary;
    }
}
