<?php

/**
 * Copyright 2013-2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 *
 * @category Horde
 * @package  Components
 * @author   Ralf Lang <ralf-lang@ralf-lang.de>
 * @license  http://www.horde.org/licenses/lgpl21 LGPL 2.1
 */

declare(strict_types=1);

namespace Horde\Components\Test\Unit\Ci\Setup;

use Horde\Components\Ci\Setup\LaneScriptGenerator;
use Horde\Components\Output;
use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\CoversClass;

/**
 * Tests for LaneScriptGenerator JSON result generation.
 *
 * @category Horde
 * @package  Components
 * @author   Ralf Lang <ralf-lang@ralf-lang.de>
 * @license  http://www.horde.org/licenses/lgpl21 LGPL 2.1
 */
#[CoversClass(LaneScriptGenerator::class)]
class LaneScriptGeneratorJsonTest extends TestCase
{
    private LaneScriptGenerator $generator;
    private Output $output;
    private string $tempDir;

    protected function setUp(): void
    {
        $this->output = $this->createMock(Output::class);
        $this->generator = new LaneScriptGenerator($this->output);
        $this->tempDir = sys_get_temp_dir() . '/lane-script-test-' . uniqid();
        mkdir($this->tempDir, 0o755, true);
    }

    protected function tearDown(): void
    {
        if (is_dir($this->tempDir)) {
            exec('rm -rf ' . escapeshellarg($this->tempDir));
        }
    }

    public function testScriptGeneratesPhpunitJsonSummary(): void
    {
        $scriptPath = $this->tempDir . '/run-lane.sh';
        $config = [
            'lane_name' => 'php8.4-dev',
            'php_version' => '8.4',
            'php_binary' => '/usr/bin/php8.4',
            'stability' => 'dev',
            'component_dir' => $this->tempDir . '/component',
            'tools_dir' => $this->tempDir . '/tools',
            'build_dir' => $this->tempDir . '/component/build',
            'components_path' => '/usr/bin/horde-components',
        ];

        $this->generator->generate($scriptPath, $config);

        $script = file_get_contents($scriptPath);

        // Should mention JSON summary file for PHPUnit
        $this->assertStringContainsString(
            'phpunit-results-summary.json',
            $script,
            'Script should mention PHPUnit JSON summary location'
        );

        // Should call horde-components qc unit which generates JSON
        $this->assertStringContainsString(
            'qc unit',
            $script,
            'Script should call qc unit command which generates JSON results'
        );
    }

    public function testScriptParsesPhpunitXmlForStatistics(): void
    {
        $scriptPath = $this->tempDir . '/run-lane.sh';
        $config = [
            'lane_name' => 'php8.4-dev',
            'php_version' => '8.4',
            'php_binary' => '/usr/bin/php8.4',
            'stability' => 'dev',
            'component_dir' => $this->tempDir . '/component',
            'tools_dir' => $this->tempDir . '/tools',
            'build_dir' => $this->tempDir . '/component/build',
            'components_path' => '/usr/bin/horde-components',
        ];

        $this->generator->generate($scriptPath, $config);

        $script = file_get_contents($scriptPath);

        // Should call qc unit which generates JSON with statistics
        $this->assertStringContainsString(
            'qc unit',
            $script,
            'Script should call qc unit which generates test statistics'
        );

        // Should mention the JSON output location
        $this->assertStringContainsString(
            'phpunit-results-summary.json',
            $script,
            'Script should mention PHPUnit JSON summary location'
        );
    }

    public function testScriptWritesPhpstanJsonSummary(): void
    {
        $scriptPath = $this->tempDir . '/run-lane.sh';
        $config = [
            'lane_name' => 'php8.4-dev',
            'php_version' => '8.4',
            'php_binary' => '/usr/bin/php8.4',
            'stability' => 'dev',
            'component_dir' => $this->tempDir . '/component',
            'tools_dir' => $this->tempDir . '/tools',
            'build_dir' => $this->tempDir . '/component/build',
            'components_path' => '/usr/bin/horde-components',
        ];

        $this->generator->generate($scriptPath, $config);

        $script = file_get_contents($scriptPath);

        // PHPStan JSON is generated by qc phpstan command
        $this->assertStringContainsString(
            'phpstan-results.json',
            $script,
            'Script should mention PHPStan JSON location'
        );
    }

    public function testScriptWritesPhpCsFixerJsonSummary(): void
    {
        $scriptPath = $this->tempDir . '/run-lane.sh';
        $config = [
            'lane_name' => 'php8.4-dev',
            'php_version' => '8.4',
            'php_binary' => '/usr/bin/php8.4',
            'stability' => 'dev',
            'component_dir' => $this->tempDir . '/component',
            'tools_dir' => $this->tempDir . '/tools',
            'build_dir' => $this->tempDir . '/component/build',
            'components_path' => '/usr/bin/horde-components',
        ];

        $this->generator->generate($scriptPath, $config);

        $script = file_get_contents($scriptPath);

        // PHP-CS-Fixer JSON is generated by qc phpcsfixer command
        $this->assertStringContainsString(
            'php-cs-fixer-results.json',
            $script,
            'Script should mention PHP-CS-Fixer JSON location'
        );
    }

    public function testJsonFormatMatchesResultCollectorExpectations(): void
    {
        $scriptPath = $this->tempDir . '/run-lane.sh';
        $config = [
            'lane_name' => 'php8.4-dev',
            'php_version' => '8.4',
            'php_binary' => '/usr/bin/php8.4',
            'stability' => 'dev',
            'component_dir' => $this->tempDir . '/component',
            'tools_dir' => $this->tempDir . '/tools',
            'build_dir' => $this->tempDir . '/component/build',
            'components_path' => '/usr/bin/horde-components',
        ];

        $this->generator->generate($scriptPath, $config);

        $script = file_get_contents($scriptPath);

        // ResultCollector expects JSON files to be created by qc commands
        // The script should call the qc commands that generate these JSON files
        $this->assertStringContainsString(
            'qc unit',
            $script,
            'Script should call qc unit which generates JSON results'
        );

        $this->assertStringContainsString(
            'qc phpstan',
            $script,
            'Script should call qc phpstan which generates JSON results'
        );
    }
}
